import subprocess
from pathlib import Path

import httpx
import pytest

from magicmd.publish.github import (
    build_authenticated_remote_url,
    create_github_pull_request,
    mask_token,
    publish_to_git_worktree,
    require_github_token,
)
from magicmd.publish.models import PublishFile, PublishPlan


def _run_git(repo: Path, *args: str) -> str:
    result = subprocess.run(
        ["git", "-C", str(repo), *args],
        check=True,
        text=True,
        capture_output=True,
    )
    return result.stdout.strip()


def _repo(tmp_path: Path) -> Path:
    repo = tmp_path / "repo"
    repo.mkdir()
    _run_git(repo, "init")
    _run_git(repo, "config", "user.email", "magicmd@example.com")
    _run_git(repo, "config", "user.name", "MagicMD")
    (repo / "README.md").write_text("# Content\n", encoding="utf-8")
    _run_git(repo, "add", "README.md")
    _run_git(repo, "commit", "-m", "Initial commit")
    return repo


def _plan(package_dir: Path) -> PublishPlan:
    article = package_dir / "article.md"
    article.write_text("# Article\n", encoding="utf-8")
    return PublishPlan(
        repo="owner/repo",
        target_dir="content/posts",
        branch="magicmd/article",
        commit_message="Add article",
        title="Article",
        platform="generic",
        source_url="https://example.com/post",
        package_dir=str(package_dir),
        files=[
            PublishFile(
                source_path=str(article),
                target_path="content/posts/article.md",
                size_bytes=article.stat().st_size,
            )
        ],
    )


def test_publish_to_git_worktree_commits_planned_files(tmp_path: Path):
    repo = _repo(tmp_path)
    package_dir = tmp_path / "package"
    package_dir.mkdir()

    result = publish_to_git_worktree(_plan(package_dir), repo)

    assert result.branch == "magicmd/article"
    assert result.commit_sha
    assert (repo / "content/posts/article.md").read_text(encoding="utf-8") == "# Article\n"
    assert _run_git(repo, "branch", "--show-current") == "magicmd/article"
    assert _run_git(repo, "log", "-1", "--pretty=%s") == "Add article"


def test_publish_to_git_worktree_rejects_existing_files_without_overwrite(tmp_path: Path):
    repo = _repo(tmp_path)
    target = repo / "content/posts"
    target.mkdir(parents=True)
    (target / "article.md").write_text("existing", encoding="utf-8")
    package_dir = tmp_path / "package"
    package_dir.mkdir()

    with pytest.raises(Exception, match="Target file already exists"):
        publish_to_git_worktree(_plan(package_dir), repo)


def test_require_github_token_rejects_missing_token(monkeypatch):
    monkeypatch.delenv("GITHUB_TOKEN", raising=False)

    with pytest.raises(Exception, match="GITHUB_TOKEN"):
        require_github_token()


def test_create_github_pull_request_uses_default_branch():
    requests = []

    def handler(request: httpx.Request) -> httpx.Response:
        requests.append(request)
        if request.method == "GET":
            return httpx.Response(200, json={"default_branch": "main"})
        return httpx.Response(201, json={"html_url": "https://github.com/owner/repo/pull/1"})

    client = httpx.Client(transport=httpx.MockTransport(handler))

    pr_url = create_github_pull_request(
        repo="owner/repo",
        branch="magicmd/article",
        title="Add article",
        body="Generated by MagicMD.",
        token="secret",
        client=client,
    )

    assert pr_url == "https://github.com/owner/repo/pull/1"
    assert requests[0].method == "GET"
    assert requests[1].method == "POST"
    assert requests[1].url.path == "/repos/owner/repo/pulls"
    assert '"head":"magicmd/article"' in requests[1].content.decode()
    assert '"base":"main"' in requests[1].content.decode()


def test_build_authenticated_remote_url_for_https_clone():
    url = build_authenticated_remote_url("owner/repo", "secret-token")

    assert url == "https://x-access-token:secret-token@github.com/owner/repo.git"


def test_mask_token_removes_token_from_messages():
    message = "https://x-access-token:secret-token@github.com/owner/repo.git failed"

    assert "secret-token" not in mask_token(message, "secret-token")
