from __future__ import annotations

import os
import shutil
import subprocess
import tempfile
from pathlib import Path

import httpx

from magicmd.publish.errors import PublishGitError, PublishGitHubError
from magicmd.publish.models import PublishPlan, PublishResult


def _run_git(repo_dir: Path, *args: str) -> str:
    result = subprocess.run(
        ["git", "-C", str(repo_dir), *args],
        text=True,
        capture_output=True,
    )
    if result.returncode != 0:
        message = (result.stderr or result.stdout).strip()
        raise PublishGitError(message or f"git {' '.join(args)} failed")
    return result.stdout.strip()


def _copy_planned_files(plan: PublishPlan, repo_dir: Path) -> None:
    for file in plan.files:
        target_path = repo_dir / file.target_path
        if target_path.exists() and not plan.overwrite:
            raise PublishGitError(f"Target file already exists: {file.target_path}")
        target_path.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(file.source_path, target_path)


def publish_to_git_worktree(plan: PublishPlan, repo_dir: Path) -> PublishResult:
    repo_dir = repo_dir.resolve()
    if not (repo_dir / ".git").exists():
        raise PublishGitError(f"Not a git repository: {repo_dir}")

    _run_git(repo_dir, "checkout", "-B", plan.branch)
    _copy_planned_files(plan, repo_dir)
    _run_git(repo_dir, "add", "--", plan.target_dir)
    status = _run_git(repo_dir, "status", "--porcelain", "--", plan.target_dir)
    if not status:
        raise PublishGitError("No publish changes to commit")
    _run_git(repo_dir, "commit", "-m", plan.commit_message)
    commit_sha = _run_git(repo_dir, "rev-parse", "HEAD")
    return PublishResult(
        repo=plan.repo,
        branch=plan.branch,
        commit_sha=commit_sha,
        files=plan.files,
    )


def require_github_token(token: str | None = None) -> str:
    resolved = token or os.environ.get("GITHUB_TOKEN", "")
    if not resolved:
        raise PublishGitHubError(
            "GITHUB_TOKEN is required for real GitHub publishing. Use --dry-run to preview only."
        )
    return resolved


def _github_headers(token: str) -> dict[str, str]:
    return {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }


def create_github_pull_request(
    repo: str,
    branch: str,
    title: str,
    body: str,
    token: str,
    client: httpx.Client | None = None,
) -> str:
    owns_client = client is None
    http_client = client or httpx.Client(timeout=20)
    try:
        repo_response = http_client.get(
            f"https://api.github.com/repos/{repo}",
            headers=_github_headers(token),
        )
        if repo_response.status_code >= 400:
            raise PublishGitHubError(f"GitHub repo lookup failed: {repo_response.text}")
        default_branch = repo_response.json().get("default_branch") or "main"

        pr_response = http_client.post(
            f"https://api.github.com/repos/{repo}/pulls",
            headers=_github_headers(token),
            json={
                "title": title,
                "head": branch,
                "base": default_branch,
                "body": body,
            },
        )
        if pr_response.status_code >= 400:
            raise PublishGitHubError(f"GitHub PR creation failed: {pr_response.text}")
        return str(pr_response.json().get("html_url", ""))
    finally:
        if owns_client:
            http_client.close()


def build_authenticated_remote_url(repo: str, token: str) -> str:
    return f"https://x-access-token:{token}@github.com/{repo}.git"


def mask_token(message: str, token: str) -> str:
    return message.replace(token, "***") if token else message


def publish_to_github(
    plan: PublishPlan,
    token: str | None = None,
) -> PublishResult:
    resolved_token = require_github_token(token)
    with tempfile.TemporaryDirectory(prefix="magicmd-publish-") as temp_dir:
        worktree = Path(temp_dir) / "repo"
        remote_url = build_authenticated_remote_url(plan.repo, resolved_token)
        try:
            subprocess.run(
                ["git", "clone", remote_url, str(worktree)],
                text=True,
                capture_output=True,
                check=True,
            )
            result = publish_to_git_worktree(plan, worktree)
            _run_git(worktree, "push", "origin", plan.branch)
            _run_git(worktree, "remote", "set-url", "origin", f"https://github.com/{plan.repo}.git")
            if plan.create_pr:
                result.pr_url = create_github_pull_request(
                    repo=plan.repo,
                    branch=plan.branch,
                    title=plan.commit_message,
                    body=f"Generated by MagicMD from {plan.source_url}",
                    token=resolved_token,
                )
            return result
        except subprocess.CalledProcessError as exc:
            message = mask_token(exc.stderr or exc.stdout or str(exc), resolved_token)
            raise PublishGitError(message) from exc
        except PublishGitError as exc:
            raise PublishGitError(mask_token(str(exc), resolved_token)) from exc
